### ISSUE TITLE
Release 0.31.7 not working

### ISSUE THREAD

**Issue by ekhvalov** [anoma/namada#2751]
Hello Team,

Today I've received a notification about new release v0.31.7.
So I decided to upgrade to it without an announce because of the release was described as a patch.
Unfortunately, after few blocks node was exited with error:
<details>
  <summary>Logs</summary>

```  
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.004] received complete proposal block             module=consensus height=83466 hash=71B35D3B47037770337449FB3D194BACCBE7988EA1224D114D73D7BBEA074F71
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.031] finalizing commit of block                   module=consensus height=83466 hash=71B35D3B47037770337449FB3D194BACCBE7988EA1224D114D73D7BBEA074F71 root=5963B0707B53F6A2A15F5636B46138062C1205D7111A04AD8CBFF6663B9501C8 num_txs=1
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.052394Z  INFO namada_apps::node::ledger::shell::finalize_block: Block height: 83466, epoch: 21, is new epoch: false.
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.081302Z  INFO namada_apps::node::ledger::shell::finalize_block: Applied 0 transactions. Wrappers: 1, successful inner txs: 0, rejected inner txs: 0, errored inner txs: 0, vp cache size: 0 - 0, tx cache size 0 - 0
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.081313Z  INFO namada_apps::node::ledger::shell::finalize_block: txs executed: 0
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.096] executed block                               module=state height=83466 num_valid_txs=1 num_invalid_txs=0
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.100923Z  INFO namada_apps::node::ledger::shell: Ethereum oracle has not yet fully processed any Ethereum blocks
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.134829Z  INFO namada_apps::node::ledger::shell: Committed block hash: 67fbaa4f0d678451d5acc88e97fb811a29bebfcded28f8479f1b8178ea68676f, height: 83466
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.175] committed state                              module=state height=83466 num_txs=1 app_hash=67FBAA4F0D678451D5ACC88E97FB811A29BEBFCDED28F8479F1B8178EA68676F
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.186] indexed block exents                         module=txindex height=83466
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.381] Error reconnecting to peer. Trying again     module=p2p tries=1 err="dial tcp 65.21.194.46:26656: i/o timeout" addr=f47f2d1fd83f8063571145f90e984a74cba6310f@65.21.194.46:26656
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.460] commit is for a block we do not know about; set ProposalBlock=nil module=consensus height=83467 commit_round=0 proposal= commit=6D5415D889BC70152C660F5AB46B51F6BE72B38D71078AB597C375DFB1E07042
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.484] received complete proposal block             module=consensus height=83467 hash=6D5415D889BC70152C660F5AB46B51F6BE72B38D71078AB597C375DFB1E07042
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.518] finalizing commit of block                   module=consensus height=83467 hash=6D5415D889BC70152C660F5AB46B51F6BE72B38D71078AB597C375DFB1E07042 root=67FBAA4F0D678451D5ACC88E97FB811A29BEBFCDED28F8479F1B8178EA68676F num_txs=2
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.550843Z  INFO namada_apps::node::ledger::shell::finalize_block: Block height: 83467, epoch: 21, is new epoch: false.
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.566] Error reconnecting to peer. Trying again     module=p2p tries=2 err="dial tcp 34.155.116.21:26656: i/o timeout" addr=10f764862481d7545323a4537da711dce111103e@34.155.116.21:26656
Feb 28 00:34:43 hz6 namada[228325]: 2024-02-28T00:34:43.582223Z  INFO namada::vm::wasm::compilation_cache::common: Trying to load Tx CCDBE81F664CA6C2CAA11426927093DC10ED95E75B3F2F45BFFD8514FEE47CD0 from file.
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping abci.socketClient for error: read message: EOF module=abci-client connection=consensus
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=abci-client connection=consensus msg="Stopping socketClient service" impl=socketClient
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] consensus connection terminated. Did the application crash? Please restart CometBFT module=proxy err="read message: EOF"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping abci.socketClient for error: read message: EOF module=abci-client connection=snapshot
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping abci.socketClient for error: read message: read tcp 127.0.0.1:55982->127.0.0.1:26658: read: connection reset by peer module=abci-client connection=query
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping abci.socketClient for error: read message: EOF module=abci-client connection=mempool
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=abci-client connection=snapshot msg="Stopping socketClient service" impl=socketClient
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=abci-client connection=query msg="Stopping socketClient service" impl=socketClient
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=abci-client connection=mempool msg="Stopping socketClient service" impl=socketClient
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] error in proxyAppConn.EndBlock               module=state err="read message: EOF"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] signal trapped                               module=main msg="captured terminated, exiting..."
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=main msg="Stopping Node service" impl=Node
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] Stopping Node                                module=main
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=events msg="Stopping EventBus service" impl=EventBus
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=pubsub msg="Stopping PubSub service" impl=PubSub
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=txindex msg="Stopping IndexerService service" impl=IndexerService
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p msg="Stopping P2P Switch service" impl="P2P Switch"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] CONSENSUS FAILURE!!!                         module=consensus err="failed to apply block; error read message: EOF" stack="
goroutine 10397 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/debug/stack.go:24 +0x65
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine.func2()
	/home/runner/work/cometbft/cometbft/consensus/state.go:732 +0x4c
panic({0xec76c0, 0xc0047e5d70})
	/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/panic.go:884 +0x213
github.com/cometbft/cometbft/consensus.(*State).finalizeCommit(0xc000155500, 0x1460b)
	/home/runner/work/cometbft/cometbft/consensus/state.go:1709 +0xf2b
github.com/cometbft/cometbft/consensus.(*State).tryFinalizeCommit(0xc000155500, 0x1460b)
	/home/runner/work/cometbft/cometbft/consensus/state.go:1609 +0x2ff
github.com/cometbft/cometbft/consensus.(*State).handleCompleteProposal(0xc000155500, 0xc001534000?)
	/home/runner/work/cometbft/cometbft/consensus/state.go:1995 +0x399
github.com/cometbft/cometbft/consensus.(*State).handleMsg(0xc000155500, {{0x12a54e0, 0xc003eb1500}, {0xc001bac000, 0x28}})
	/home/runner/work/cometbft/cometbft/consensus/state.go:842 +0x1b7
github.com/cometbft/cometbft/consensus.(*State).receiveRoutine(0xc000155500, 0x0)
	/home/runner/work/cometbft/cometbft/consensus/state.go:768 +0x3f0
created by github.com/cometbft/cometbft/consensus.(*State).OnStart
	/home/runner/work/cometbft/cometbft/consensus/state.go:379 +0x12d
"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=consensus wal=/home/namada/.local/share/namada/shielded-expedition.88f17d1d14/cometbft/data/cs.wal/wal msg="Stopping baseWAL service" impl=baseWAL
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=454c26734c61ff98c1db0b34559b8a307a18a319@34.88.120.47:43508 msg="Stopping Peer service" impl="Peer{MConn{34.88.120.47:43508} 454c26734c61ff98c1db0b34559b8a307a18a319 in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=454c26734c61ff98c1db0b34559b8a307a18a319@34.88.120.47:43508 msg="Stopping MConnection service" impl=MConn{34.88.120.47:43508}
Feb 28 00:34:43 hz6 systemd[1]: namada.service: Main process exited, code=killed, status=11/SEGV
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=38afb25360d9a698caf5a8934f4484e676352b8e@89.58.28.79:26656 msg="Stopping Peer service" impl="Peer{MConn{89.58.28.79:26656} 38afb25360d9a698caf5a8934f4484e676352b8e out}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=consensus wal=/home/namada/.local/share/namada/shielded-expedition.88f17d1d14/cometbft/data/cs.wal/wal msg="Stopping Group service" impl=Group
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=38afb25360d9a698caf5a8934f4484e676352b8e@89.58.28.79:26656 msg="Stopping MConnection service" impl=MConn{89.58.28.79:26656}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=ff0269406b70b76b991c8eb89918042554ecc26d@65.108.13.212:26656 msg="Stopping Peer service" impl="Peer{MConn{65.108.13.212:26656} ff0269406b70b76b991c8eb89918042554ecc26d out}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=ff0269406b70b76b991c8eb89918042554ecc26d@65.108.13.212:26656 msg="Stopping MConnection service" impl=MConn{65.108.13.212:26656}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=35f12dc30ae68c82e79f54e223423c0f6fe311f8@34.163.21.255:33074 msg="Stopping MConnection service" impl=MConn{34.163.21.255:33074}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=35f12dc30ae68c82e79f54e223423c0f6fe311f8@34.163.21.255:33074 msg="Stopping Peer service" impl="Peer{MConn{34.163.21.255:33074} 35f12dc30ae68c82e79f54e223423c0f6fe311f8 in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=38cdd5bc9fd11a7bbefd42400806fe6e317606a4@104.251.222.134:54740 msg="Stopping MConnection service" impl=MConn{104.251.222.134:54740}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] Unsubscribe from query                       module=rpc remote=127.0.0.1:37544 query="message.module = 'interchainquery'"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping peer for error                      module=p2p peer="Peer{MConn{104.251.222.134:54740} 38cdd5bc9fd11a7bbefd42400806fe6e317606a4 in}" err="read tcp 88.198.13.197:26656->104.251.222.134:54740: use of closed network connection"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:37544 method=unsubscribe
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=38cdd5bc9fd11a7bbefd42400806fe6e317606a4@104.251.222.134:54740 msg="Stopping Peer service" impl="Peer{MConn{104.251.222.134:54740} 38cdd5bc9fd11a7bbefd42400806fe6e317606a4 in}"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] error while stopping peer                    module=p2p error="already stopped"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=0d0c3f16328f99411123bb75967f2cfdaf99c72e@34.38.207.143:58014 msg="Stopping MConnection service" impl=MConn{34.38.207.143:58014}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=0d0c3f16328f99411123bb75967f2cfdaf99c72e@34.38.207.143:58014 msg="Stopping Peer service" impl="Peer{MConn{34.38.207.143:58014} 0d0c3f16328f99411123bb75967f2cfdaf99c72e in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=677f60b8f13e4a1e1b318d21aac7b21421dd7bce@135.181.32.162:35158 msg="Stopping Peer service" impl="Peer{MConn{135.181.32.162:35158} 677f60b8f13e4a1e1b318d21aac7b21421dd7bce in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=677f60b8f13e4a1e1b318d21aac7b21421dd7bce@135.181.32.162:35158 msg="Stopping MConnection service" impl=MConn{135.181.32.162:35158}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=16bff97cfaa6514e42afe7a966b04e168bb529cc@34.175.46.78:60536 msg="Stopping Peer service" impl="Peer{MConn{34.175.46.78:60536} 16bff97cfaa6514e42afe7a966b04e168bb529cc in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] New websocket connection                     module=rpc-server protocol=websocket remote=127.0.0.1:39718
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=16bff97cfaa6514e42afe7a966b04e168bb529cc@34.175.46.78:60536 msg="Stopping MConnection service" impl=MConn{34.175.46.78:60536}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service start                                module=rpc-server protocol=websocket remote=127.0.0.1:39718 msg="Starting wsConnection service" impl=wsConnection
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=0a4ae55f81a2d5541c9f96274d1e51b1078c99df@167.235.35.48:26656 msg="Stopping MConnection service" impl=MConn{167.235.35.48:26656}
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] Stopping peer for error                      module=p2p peer="Peer{MConn{167.235.35.48:26656} 0a4ae55f81a2d5541c9f96274d1e51b1078c99df out}" err="read tcp 88.198.13.197:54600->167.235.35.48:26656: use of closed network connection"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] error while stopping peer                    module=p2p error="already stopped"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=0a4ae55f81a2d5541c9f96274d1e51b1078c99df@167.235.35.48:26656 msg="Stopping Peer service" impl="Peer{MConn{167.235.35.48:26656} 0a4ae55f81a2d5541c9f96274d1e51b1078c99df out}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] Client closed the connection                 module=rpc-server protocol=websocket remote=127.0.0.1:37544
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] Reconnecting to peer                         module=p2p addr=0a4ae55f81a2d5541c9f96274d1e51b1078c99df@167.235.35.48:26656
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=rpc-server protocol=websocket remote=127.0.0.1:37544 msg="Stopping wsConnection service" impl=wsConnection
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.739] error while stopping connection              module=rpc-server protocol=websocket error="already stopped"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=1cd960d9fc9ba1aa8fec501efdbc6344029773d8@35.187.51.194:36858 msg="Stopping Peer service" impl="Peer{MConn{35.187.51.194:36858} 1cd960d9fc9ba1aa8fec501efdbc6344029773d8 in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.739] service stop                                 module=p2p peer=1cd960d9fc9ba1aa8fec501efdbc6344029773d8@35.187.51.194:36858 msg="Stopping MConnection service" impl=MConn{35.187.51.194:36858}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=p2p peer=0c4ce0c5ceb022564b111a4e4d0c0a66a9567dbe@65.109.117.113:26656 msg="Stopping Peer service" impl="Peer{MConn{65.109.117.113:26656} 0c4ce0c5ceb022564b111a4e4d0c0a66a9567dbe out}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=p2p peer=0c4ce0c5ceb022564b111a4e4d0c0a66a9567dbe@65.109.117.113:26656 msg="Stopping MConnection service" impl=MConn{65.109.117.113:26656}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=p2p peer=6da14df5354b2120aa83dc36fe2ffcc16ad36b3e@34.76.66.157:34756 msg="Stopping Peer service" impl="Peer{MConn{34.76.66.157:34756} 6da14df5354b2120aa83dc36fe2ffcc16ad36b3e in}"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=p2p peer=6da14df5354b2120aa83dc36fe2ffcc16ad36b3e@34.76.66.157:34756 msg="Stopping MConnection service" impl=MConn{34.76.66.157:34756}
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=consensus msg="Stopping Consensus service" impl=ConsensusReactor
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=consensus msg="Stopping State service" impl=ConsensusState
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=consensus msg="Stopping TimeoutTicker service" impl=TimeoutTicker
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] Subscribe to query                           module=rpc remote=127.0.0.1:39718 query="tm.event = 'NewBlock'"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:39718 method=subscribe
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=evidence msg="Stopping Evidence service" impl=Evidence
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=statesync msg="Stopping StateSync service" impl=StateSync
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=pex msg="Stopping PEX service" impl=PEX
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=p2p book=/home/namada/.local/share/namada/shielded-expedition.88f17d1d14/cometbft/config/addrbook.json msg="Stopping AddrBook service" impl=AddrBook
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] service stop                                 module=blockchain msg="Stopping Reactor service" impl=Reactor
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.740] Error stopping pool                          module=blockchain err="already stopped"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] Closing rpc listener                         module=main listener="&{Listener:0xc0004e0258 sem:0xc0016e42a0 closeOnce:{done:0 m:{state:0 sema:0}} done:0xc0016e4300}"
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.740] Stopped accept routine, as transport is closed module=p2p numPeers=0
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] RPC HTTP server stopped                      module=rpc-server err="accept tcp [::]:26657: use of closed network connection"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] Saving AddrBook to file                      module=p2p book=/home/namada/.local/share/namada/shielded-expedition.88f17d1d14/cometbft/config/addrbook.json size=1094
Feb 28 00:34:43 hz6 namada[228367]: E[2024-02-28|00:34:43.740] Error serving server                         module=main err="accept tcp [::]:26657: use of closed network connection"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] Subscribe to query                           module=rpc remote=127.0.0.1:39718 query="message.module = 'ibc_client'"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:39718 method=subscribe
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] Subscribe to query                           module=rpc remote=127.0.0.1:39718 query="message.module = 'ibc_connection'"
Feb 28 00:34:43 hz6 namada[228367]: I[2024-02-28|00:34:43.740] WSJSONRPC                                    module=rpc-server protocol=websocket remote=127.0.0.1:39718 method=subscribe
Feb 28 00:34:43 hz6 systemd[1]: namada.service: Failed with result 'signal'.
Feb 28 00:34:43 hz6 systemd[1]: namada.service: Consumed 3min 41.367s CPU time.
```
</details>

Public key: `tpknam1qzqhv7udzne2yg2xllcnu657lcedra8rml62ep4t93t2yz20926acmuxv4e`
Validator address: `tnam1q9t7q2sqyrvjuafyu2gpwg8l5pwwfy9y9qx3ev5g`

**Comment by tzemanovic** [comment]
hi, the issue is most likely with wasm compilation cache and we have a patch coming that should prevent this. You can clear it manually (`vp_wasm_cache` and `tx_wasm_cache` in the chain dir) and try to resume

**Comment by ekhvalov** [comment]
You want me to clear cache and try 0.31.7 again, or it is just a recommendation for 0.31.6?
