### ISSUE TITLE
Cannot generate encoding specs for `ProtocolTxType`

### ISSUE THREAD

**Issue by james-chf** [anoma/namada#453]
When generating the encoding specs for `eth-bridge-integration` (running `RUST_BACKTRACE=1 cargo run --bin namada_encoding_spec`), we get an error:
```
     Running `target/debug/namada_encoding_spec`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Struct { fields: NamedFields([("signatures", "HashMap<Address, Signature>"), ("events", "Vec<MultiSignedEthEvent>")]) }`,
 right: `Struct { fields: NamedFields([("signatures", "HashMap<Address, Signature>"), ("voting_powers", "HashMap<EthAddress, VotingPower>")]) }`: Redefining type schema for the same type name. Types with the same names are not supported.', /Users/main/.cargo/git/checkouts/borsh-rs-20b3a485f3c9d3de/cd5223e/borsh/src/schema.rs:87:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:181:5
   4: borsh::schema::BorshSchema::add_definition
             at /Users/main/.cargo/git/checkouts/borsh-rs-20b3a485f3c9d3de/cd5223e/borsh/src/schema.rs:87:17
   5: <namada::types::vote_extensions::validator_set_update::VextDigest as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/vote_extensions/validator_set_update.rs:29:68
   6: <<namada::types::transaction::protocol::protocol_txs::ProtocolTxType as borsh::schema::BorshSchema>::add_definitions_recursively::ProtocolTxTypeValidatorSetUpdate as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/transaction/protocol.rs:74:62
   7: <namada::types::transaction::protocol::protocol_txs::ProtocolTxType as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/transaction/protocol.rs:74:62
   8: <namada::types::transaction::protocol::protocol_txs::ProtocolTx as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/transaction/protocol.rs:44:62
   9: <<namada::types::transaction::tx_types::TxType as borsh::schema::BorshSchema>::add_definitions_recursively::TxTypeProtocol as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/transaction/mod.rs:233:62
  10: <namada::types::transaction::tx_types::TxType as borsh::schema::BorshSchema>::add_definitions_recursively
             at ./shared/src/types/transaction/mod.rs:233:62
  11: borsh::schema::BorshSchema::schema_container
             at /Users/main/.cargo/git/checkouts/borsh-rs-20b3a485f3c9d3de/cd5223e/borsh/src/schema.rs:99:9
  12: namada_encoding_spec::main
             at ./encoding_spec/src/main.rs:84:26
  13: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

It seems to be because we have two types with the name `VextDigest` embedded in our `ProtocolTxType` - renaming one of them gets rid of the issue, but maybe that isn't the best way to deal with it, as `VextDigest` is an appropriate name in context.

https://github.com/anoma/namada/blob/4f71a6617ab550c0beabe6359afab671509ee43a/shared/src/types/transaction/protocol.rs#L74-L86

**Comment by sug0** [comment]
FIxed in https://github.com/anoma/namada/pull/461
